---
title: "About"
---

## Background

I grew up in Rwanda and studied Computer Science at the African Leadership University. Before starting the MDS, I worked as a Software Engineer, building and maintaining data-driven systems and automation tools. I’ve also been involved in the tech community through organizations like Google Developers Group Kigali, that organize events and mentor students and early-career developers.

## Why Data Science

My interest in data science grew from seeing how much potential data has to improve the systems around us. Through my work in software engineering, I became increasingly interested in not just building systems that collect data, but using that data to understand problems, make better decisions, and create meaningful solutions. I joined the MDS to strengthen my skills in statistics, machine learning, and data analysis and to make the transition from software engineering into data-focused roles.

## Outside of Data Science

Outside of school and work, I enjoy spending time with friends, exploring new places, and discovering new music especially pop music and afrobeats. I also enjoy being involved in community activities and meeting people from different backgrounds. On a quiet weekend, though, I’m just as happy staying in, watching a good show, and recharging.

